Upgrade pulsar to 2.8.0-SNAPSHOT (b6ca040)
https://github.com/apache/pulsar/pull/10647 modified PulsarMockBookKeeper and BookKeeperClientFactory interface, so this PR introduced
bookkeeper-common dependency and excludes the netty-common dependency to avoid conflict like

> java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.putByte(Ljava/lang/Object;JB)V

Another change is downgrade Jackson version from 2.12.1 to 2.11.1. Otherwise, the following error would be encountered:

> java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature